"""REMOVE: sqlite_autoincrement

Revision ID: 72db5c7b74f9
Revises: 6c5aae0b6901
Create Date: 2026-06-10 11:37:54.003823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72db5c7b74f9'
down_revision = '6c5aae0b6901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
